@startuml createProjectUC


|Менеджер|
start
:Пише концепцію проекту;

|Система|
:Інтерпретує концепцію;
:Показує концепцію схематично;

|Менеджер|
:Підтверджує;

|Система|
:Зберігає план в базу даних;

|Менеджер|
stop

right footer
Організація баз даних.
НТУУ "КПІ ім.І.Сікорського"
Київ 2020 
end footer
@enduml
