@startuml runProject

|Менеджер|
start
:Обирає сценарій зі списку;

|Система|
:Інтерпретує сценарій;
:Показує сценарій схематично;

|Менеджер|
:Підтверджує;

|Система|
:Генерує завдання і зберігає їх в базу даних;

|Менеджер|
stop

right footer
Організація баз даних.
НТУУ "КПІ ім.І.Сікорського"
Київ 2020 
end footer
@enduml
