@startuml
|Користувач|
start
:Обирає певну задачу;
:Натискає на червоний хрестик;

|Система|
:Видаляє задачу;

|Користувач|
stop

right footer
Організація баз даних.
НТУУ "КПІ ім.І.Сікорського"
Київ 2020 
end footer
@enduml
