@startuml getTask


|Система|

|Робітник|
start
:Ініціює процедуру;

|Система|

:Посилає повідомлення робітнику;

|Робітник|
:Підтверджує отримання;

|Система|
:Оновлює стан задачі;

|Робітник|
stop

right footer
Організація баз даних.
НТУУ "КПІ ім.І.Сікорського"
Київ 2020 
end footer
@enduml
