@startuml resolveTask

|Робітник|
start
:Вносить в систему артефакти;

|Система|
:Підтверджує отримання;
:Оновлює стан задачі;
:Надсилає повідомлення відповідальному тестувальнику;

|Робітник|
stop

right footer
Організація баз даних.
НТУУ "КПІ ім.І.Сікорського"
Київ 2020 
end footer
@enduml
