@startuml handleResult


|Тестувальник|
start
:Натискає кнопку;
:Ініціює процедуру;

|Система|
:Надсилає повідомлення тестувальнику;

|Тестувальник|
:Підтверджує отримання;
:Перевіряє якість виконання;
:Передає дані про якість
виконання в систему;
note right #ffaaaa
<font color=red><b>Може ініціювати EX_1
<font color=red><b>ситуацію "Обробка помилок"
end note

|Система|
:Збергає дані про якість
виконання в базу даних;
stop

right footer
Організація баз даних.
НТУУ "КПІ ім.І.Сікорського"
Київ 2020 
end footer
@enduml
