@startuml handleErrorsUC


|Тестувальник|
start
:Ініціює процедуру;
note right #ffaaaa
EX_2 Може додати свій сценарій її вирішення
end note

|Система|
:Оновлює стан задачі;
:Розсилає повідомлення 
про нові задачі за сценарієм;

|Тестувальник|
stop

right footer
Організація баз даних.
НТУУ "КПІ ім.І.Сікорського"
Київ 2020 
end footer
@enduml
