@startuml runProject

|Менеджер|
start
:Натискає кнопку;
:Ініціює процедуру;

|Система|
:Оновлює стан завдання;
:Надсилає повідомлення менеджеру;

|Менеджер|
:Отримує повідомлення;
:Формує сценарій вирішення проблеми;
:Підтверджує його;

|Система|
:Оновлює стан завдання;
:Розсилає повідомлення про нові завдання за сценарієм;

|Менеджер|
stop


right footer
Організація баз даних.
НТУУ "КПІ ім.І.Сікорського"
Київ 2020 
end footer
@enduml
