@startuml

actor "Робітник" as Worker
actor "Менеджер" as Manager
actor "Тестувальник" as QA
actor "Змінює статус завдань" as red

usecase "<b>UC_1</b>\n Редагувати план проекту" as UC_1
usecase "<b>UC_2</b>\n Запускати проект" as UC_2
usecase "<b>UC_3</b>\n Отримання задачі" as UC_3
usecase "<b>UC_4</b>\n Передача результату" as UC_4
usecase "<b>UC_5</b>\n Перевіряти виконання" as UC_5
usecase "<b>UC_6</b>\n Обробляти помилки" as UC_6




Manager -d-> UC_2
Manager -u-> UC_1
Manager -u-|> red

Worker -l-> UC_3
Worker -r-> UC_4

QA -u-> UC_5
QA -d-> UC_6
QA -d-|> red


right footer
Організація баз даних.
НТУУ "КПІ ім.І.Сікорського"
Київ 2020 
end footer
@enduml
